config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => 'users/sessions' }

  get 'check_time_until_logout' => 'session_timeout#check_time_until_logout', :constraints => { :only_ajax => true }
  get 'reset_user_clock' => 'session_timeout#reset_user_clock', :constraints => { :only_ajax => true }

  match "hbx_admin/update_aptc_csr" => "hbx_admin#update_aptc_csr", as: :update_aptc_csr, via: [:get, :post]
  match "hbx_admin/edit_aptc_csr" => "hbx_admin#edit_aptc_csr", as: :edit_aptc_csr, via: [:get, :post], defaults: { format: 'js' }
  match "hbx_admin/calculate_aptc_csr" => "hbx_admin#calculate_aptc_csr", as: :calculate_aptc_csr, via: :get
  post 'show_hints' => 'welcome#show_hints', :constraints => { :only_ajax => true }

  namespace :users do
    resources :orphans, only: [:index, :show, :destroy]
  end
  
  resources :users do
    member do
      get :reset_password, :lockable, :confirm_lock, :login_history, :change_username_and_email, :edit
      put :confirm_reset_password, :confirm_change_username_and_email, :update
      post :unlock, :change_password
    end
  end

  resources :saml, only: [] do
    collection do
      post :login
      get :logout
      get :navigate_to_assistance
    end
  end

  get 'payment_transactions/generate_saml_response', to: 'payment_transactions#generate_saml_response'

  namespace :exchanges do

    resources :inboxes, only: [:show, :destroy]
    resources :announcements, only: [:index, :create, :destroy] do
      get :dismiss, on: :collection
    end
    resources :agents_inboxes, only: [:show, :destroy]

    resources :residents, only: [:create, :edit, :update] do
      get :search, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :begin_resident_enrollment, on: :collection
      get :resume_resident_enrollment, on: :collection
      get :ridp_bypass, on: :collection
      get :find_sep, on: :collection
    end

    resources :hbx_profiles do
      root 'hbx_profiles#show'

      collection do
        get :family_index
        get :family_index_dt
        get :outstanding_verification_dt
        post :families_index_datatable
        get :employer_index
        get :employer_poc
        post :employer_poc_datatable
        get :employer_invoice
        post :employer_invoice_datatable
        post :generate_invoice
        post :disable_ssn_requirement
        get :broker_agency_index
        get :general_agency_index
        get :issuer_index
        get :product_index
        get :configuration
        post :set_date
        post :update_setting
        get :staff_index
        get :assister_index
        get :request_help
        get :aptc_csr_family_index
        get :binder_index
        get :binder_index_datatable
        post :binder_paid
        get :cancel_enrollment
        post :update_cancel_enrollment
        get :terminate_enrollment
        post :update_terminate_enrollment
        post :add_new_sep
        get :update_effective_date
        get :calculate_sep_dates
        get :add_sep_form
        get :hide_form
        get :show_sep_history
        get :get_user_info
        get :identity_verification
        post :identity_verification_datatable
        get :user_account_index
        get :new_eligibility
      end

      member do
        post :transmit_group_xml
        get :transmit_group_xml
        get :home
        get :inbox
      end

      resources :hbx_staff_roles do
      end
    end

    resources :employer_applications do
      put :terminate
      put :cancel
      put :reinstate
    end

    resources :agents do
      collection do
        get :home
        get :begin_consumer_enrollment
        get :begin_employee_enrollment
        get :resume_enrollment
        get :show
      end
      member do
        get :inbox
      end
    end

    resources :broker_applicants

  end

  namespace :insured do
    get 'verification_documents/upload', to: 'verification_documents#upload'
    post 'verification_documents/upload', to: 'verification_documents#upload'
    get 'verification_documents/download/:key', to: 'verification_documents#download'
    get 'paper_applications/upload', to: 'paper_applications#upload'
    post 'paper_applications/upload', to: 'paper_applications#upload'
    get 'paper_applications/download/:key', to: 'paper_applications#download'
    get 'ridp_documents/upload', to: 'ridp_documents#upload'
    post 'ridp_documents/upload', to: 'ridp_documents#upload'
    get 'ridp_documents/download/:key', to: 'ridp_documents#download'
    resources :ridp_documents, only: [:destroy]

    resources :plan_shoppings, :only => [:show] do
      member do
        get 'plans'
        get 'receipt'
        get 'print_waiver'
        post 'checkout'
        get 'thankyou'
        post 'waive'
        post 'terminate'
        post 'set_elected_aptc'
        get 'plan_selection_callback'
      end
    end

    resources :interactive_identity_verifications, only: [:create, :new, :update] do
      collection do
        get 'failed_validation'
        get 'service_unavailable'
      end
    end

    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :families, only: [:show] do
      get 'new'
      member do
        delete 'delete_consumer_broker'
        get 'generate_out_of_pocket_url'
      end

      collection do
        get 'home'
        get 'manage_family'
        get 'personal'
        get 'inbox'
        get 'brokers'
        get 'verification'
        get 'upload_application'
        get 'document_upload'
        get 'find_sep'
        post 'record_sep'
        get 'check_qle_date'
        get 'check_move_reason'
        get 'check_insurance_reason'
        get 'check_marriage_reason'
        get 'purchase'
        get 'family'
        get 'upload_notice_form'
        post 'upload_notice'
        get 'transition_family_members'
        post 'transition_family_members_update'
      end

      resources :people do
        collection do
          get 'search'
        end
      end
    end

    resources :consumer_role, controller: 'consumer_roles', only: [:create, :edit, :update] do
      get :ssn_taken, on: :collection
      get :search, on: :collection
      get :privacy, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :ridp_agreement, on: :collection
      post :update_application_type
      get :upload_ridp_document, on: :collection
      get :immigration_document_options, on: :collection
    end

    resources :employee, :controller=>"employee_roles", only: [:create, :edit, :update, :show] do
      collection do
        get 'new_message_to_broker'
        post 'send_message_to_broker'
        post :match
        get 'search'
        get 'privacy'
        get 'welcome'
      end
    end

    root 'families#home'

    resources :family_members do
      get :resident_index, on: :collection
      get :new_resident_dependent, on: :collection
      get :edit_resident_dependent, on: :member
      get :show_resident_dependent, on: :member
    end

    resources :group_selections, controller: "group_selection", only: [:new, :create] do
      collection do
        post :terminate
        get :terminate_selection
        get :terminate_confirm
      end
    end

  end

  namespace :employers do
    post 'search', to: 'employers#search'
    root 'employer_profiles#new'

    resources :premium_statements, :only => [:show]

    resources :employer_staff_roles, :only => [:create, :destroy] do
      member do
        get :approve
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'match'
      end
    end
    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :employer_profiles do
      get 'new'
      get 'my_account'
      get 'show_profile'
      get 'link_from_quote'
      get 'consumer_override'
      get 'export_census_employees'
      get 'bulk_employee_upload_form'
      post 'bulk_employee_upload'
      member do
        get "download_invoice"
        post 'generate_checkbook_urls'
      end
      collection do
        get 'welcome'
        get 'search'
        post 'match'
        get 'inbox'
      end
      resources :plan_years do
        get 'reference_plans'
        get 'dental_reference_plans'
        get 'generate_dental_carriers_and_plans'
        get 'plan_details' => 'plan_years#plan_details', on: :collection
        get 'recommend_dates', on: :collection
        get 'reference_plan_options', on: :collection
        post 'revert'
        post 'publish'
        post 'force_publish'
        get 'search_reference_plan', on: :collection
        post 'make_default_benefit_group'
        post 'delete_benefit_group'
        get 'calc_employer_contributions', on: :collection
        get 'calc_offered_plan_contributions', on: :collection
        get 'employee_costs', on: :collection
        get 'reference_plan_summary', on: :collection

      end

      resources :broker_agency, only: [:index, :show, :create] do
        collection do
          get :active_broker
        end
        get :terminate
      end

      resources :census_employees, only: [:new, :create, :edit, :update, :show] do
        get :delink
        get :terminate
        get :rehire
        get :cobra
        get :cobra_reinstate
        get :benefit_group, on: :member
      end
    end
  end

  match 'broker_registration', to: 'broker_agencies/broker_roles#new_broker_agency', via: [:get]

  namespace :carriers do
    resources :carrier_profiles do
    end
  end

  namespace :broker_agencies do
    root 'profiles#new'
    resources :inboxes, only: [:new, :create, :show, :destroy] do
      get :msg_to_portal
    end
    resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
      get :inbox

      collection do
        get :family_index
        get :employers

app/models/forms/plan_year_form.rb
module Forms
  class PlanYearForm < SimpleDelegator
     def initialize(py)
       super(py)
     end

     def carrier_plans_for(c_profile_id)
       ::Plan.valid_shop_health_plans("carrier", c_profile_id, start_on.year).map{|plan| ["#{::Organization.valid_carrier_names[plan.carrier_profile_id.to_s]} - #{plan.name}", plan.id.to_s]}
     end

     def metal_level_plans_for(metal_level)
       ::Plan.valid_shop_health_plans("metal_level", metal_level, start_on.year).map{|plan| ["#{::Organization.valid_carrier_names[plan.carrier_profile_id.to_s]} - #{plan.name}", plan.id.to_s]}
     end

     def self.model_name
       ::PlanYear.model_name
     end

     def assign_plan_year_attributes(atts = {})
       atts.each_pair do |k, v|
         self.send("#{k}=".to_sym, v)
       end
     end

     def self.build(employer_profile, atts)
       new_py = employer_profile.plan_years.new
       self.new(new_py).tap do |new_proxy|
         new_proxy.assign_plan_year_attributes(atts)
       end
     end

     def self.rebuild(plan_year, atts)
       self.new(plan_year).tap do |proxy|
         proxy.assign_plan_year_attributes(atts)
       end
     end
  end
end

app/models/plan_selection.rb
class PlanSelection
  attr_reader :plan, :hbx_enrollment

  def initialize(enrollment, pl)
    @hbx_enrollment = enrollment
    @plan = pl
  end

  def employee_is_shopping_before_hire?
    hbx_enrollment.employee_role.present? && hbx_enrollment.employee_role.hired_on > TimeKeeper.date_of_record
  end

  def may_select_coverage?
    hbx_enrollment.may_select_coverage?
  end

  def can_apply_aptc?(shopping_tax_household, elected_aptc)
    return false if hbx_enrollment.is_shop?
    shopping_tax_household.present? && elected_aptc > 0 && plan.can_use_aptc?
  end

  def apply_aptc_if_needed(shopping_tax_household, elected_aptc, max_aptc)
    if can_apply_aptc?(shopping_tax_household, elected_aptc)
      decorated_plan = UnassistedPlanCostDecorator.new(plan, hbx_enrollment, elected_aptc, shopping_tax_household)
      hbx_enrollment.update_hbx_enrollment_members_premium(decorated_plan)
      hbx_enrollment.update_current(applied_aptc_amount: decorated_plan.total_aptc_amount, elected_aptc_pct: elected_aptc/max_aptc)
    end
  end

  def select_plan_and_deactivate_other_enrollments(previous_enrollment_id, market_kind)
    hbx_enrollment.update_current(plan_id: plan.id)
    # hbx_enrollment.inactive_related_hbxs
    # hbx_enrollment.inactive_pre_hbx(previous_enrollment_id)

    qle = hbx_enrollment.is_special_enrollment?
    if qle
      sep_id = hbx_enrollment.is_shop? ? hbx_enrollment.family.earliest_effective_shop_sep.id
      : hbx_enrollment.family.earliest_effective_ivl_sep.id

      hbx_enrollment.special_enrollment_period_id = sep_id
    end
    hbx_enrollment.aasm_state = 'auto_renewing' if hbx_enrollment.is_active_renewal_purchase?
    if enrollment_members_verification_status(market_kind)
      hbx_enrollment.update_attributes!(is_any_enrollment_member_outstanding: true)
    end
    hbx_enrollment.select_coverage!(qle: qle)
    if market_kind == 'shop'
      plan_year = hbx_enrollment.benefit_group.plan_year
      if plan_year.termination_pending?
        plan_year.terminate_employee_enrollments(plan_year.end_on, transmit_xml:true)
      end
    end
  end
  
  def enrollment_members_verification_status(market_kind)
    members = hbx_enrollment.hbx_enrollment_members.flat_map(&:person).flat_map(&:consumer_role)
    if market_kind == "individual"
      return  (members.compact.present? && (members.any?(&:verification_outstanding?) || members.any?(&:verification_period_ended?)))
    else
      return false
    end
  end

  def self.for_enrollment_id_and_plan_id(enrollment_id, plan_id)
    plan = Plan.find(plan_id)
    hbx_enrollment = HbxEnrollment.find(enrollment_id)
    self.new(hbx_enrollment, plan)
  end

  def family
    hbx_enrollment.family
  end

  def verify_and_set_member_coverage_start_dates
    if existing_coverage.present? && (existing_coverage.plan.hios_id == plan.hios_id)
      hbx_enrollment = set_enrollment_member_coverage_start_dates
      hbx_enrollment.predecessor_enrollment_id = existing_coverage._id
    end
  end

  def same_plan_enrollment
    return @same_plan_enrollment if defined? @same_plan_enrollment

    @same_plan_enrollment = family.active_household.hbx_enrollments.new(hbx_enrollment.dup.attributes)
    @same_plan_enrollment.hbx_enrollment_members = build_hbx_enrollment_members
    @same_plan_enrollment = set_enrollment_member_coverage_start_dates(@same_plan_enrollment)

    @same_plan_enrollment
  end

  def build_hbx_enrollment_members
    hbx_enrollment.hbx_enrollment_members.collect do |hbx_enrollment_member|
      HbxEnrollmentMember.new({
        applicant_id: hbx_enrollment_member.applicant_id,
        eligibility_date: hbx_enrollment.effective_on,
        coverage_start_on: hbx_enrollment.effective_on,
        is_subscriber: hbx_enrollment_member.is_subscriber
      })
    end
  end

  def existing_coverage
    existing_enrollment_for_covered_individuals
  end

  def set_enrollment_member_coverage_start_dates(enrollment_obj = hbx_enrollment)

    if existing_coverage.present?
      previous_enrollment_members = existing_coverage.hbx_enrollment_members

      enrollment_obj.hbx_enrollment_members.each do |member|
        matched = previous_enrollment_members.detect{|enrollment_member| enrollment_member.hbx_id == member.hbx_id}

        if matched
          member.coverage_start_on = matched.coverage_start_on || existing_coverage.effective_on
        end
      end
    end

    enrollment_obj
  end

  def existing_enrollment_for_covered_individuals
    previous_active_coverages.detect{|en|
      (en.hbx_enrollment_members.collect(&:hbx_id) & hbx_enrollment.hbx_enrollment_members.collect(&:hbx_id)).present? && en.id != hbx_enrollment.id
    }
  end

  def previous_active_coverages
    if hbx_enrollment.is_shop?
      coverage_year_start = hbx_enrollment.benefit_group.start_on
    else
      coverage_year_start = hbx_enrollment.effective_on.beginning_of_year
    end

    family.active_household.hbx_enrollments.where({
      :_id.ne => hbx_enrollment.id,
      :kind => hbx_enrollment.kind,
      :coverage_kind => hbx_enrollment.coverage_kind,
      :effective_on.gte => coverage_year_start,
      }).or(
        {:aasm_state.in => HbxEnrollment::ENROLLED_STATUSES},
        {:aasm_state.in => HbxEnrollment::TERMINATED_STATUSES, :terminated_on.gte => hbx_enrollment.effective_on.prev_day}
      ).order("effective_on DESC")
  end

  def family
    hbx_enrollment.family
  end
end

app/views/employers/plan_years/plan_selection/_dental_plans.html.erb
<% if @nav_option != 'custom' %>
<br/>
<div class="col-xs-12">
  <h1>
    Select Reference Plan
  </h1>
  <h4>
    The reference plan is used to cap employer costs. You’ll choose a reference plan. Then, your contribution towards employee premiums will be applied to the reference plan you choose regardless of which plans your employees select.
  </h4>
</div>
<br class="clear"/>
<br>
<% end %>
<% @dental_plans.each do |p| %>
  <div class="col-xs-4">
    <div class="col-xs-12 reference-plan">
      <div class="col-xs-2">
        <% if @nav_option == 'custom' %>
          <% if @is_edit == false || @elected_plans.blank? %>
            <%= check_box_tag "plan_year[benefit_groups_attributes][0][elected_dental_reference_plan_ids][]", p.id, true %>
            <%= label_tag "plan_year[benefit_groups_attributes][0][elected_dental_reference_plan_#{p.id}][]" do %>
              <i class="fa fa-check-square-o fa-2x"></i>
              <i class="fa fa-square-o fa-2x"></i>
            <% end %>
          <% else %>
            <% checked = true if @elected_plans.include?(p.id) %>
            <%= check_box_tag "plan_year[benefit_groups_attributes][0][elected_dental_reference_plan_ids][]", p.id, checked %>
            <%= label_tag "plan_year[benefit_groups_attributes][0][elected_dental_reference_plan_#{p.id}][]" do %>
              <i class="fa fa-check-square-o fa-2x"></i>
              <i class="fa fa-square-o fa-2x"></i>
            <% end %>
          <% end %>
        <% else %>
          <%= radio_button "#{@location_id}", :dental_reference_plan_id, p.id %>
          <%= label_tag "#{@location_id}[dental_reference_plan_id]" do %>
          <i class="fa fa-circle-o"></i>
          <i class="fa fa-dot-circle-o"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col-xs-10">
        <div class="panel row">
          <div class="panel-heading">
            <h3><%= p.name %></h3>
          </div>
          <div class="panel-body">
            <span class="plan-label">Type: </span><span><%= p.plan_type %></span><br>
            <span class="plan-label">Carrier: </span><span><%= p.carrier_profile.legal_name %></span><br>
            <span class="plan-label">Level: </span><span><%= display_dental_metal_level(p) %></span><br>
            <span class="plan-label">Network: </span><span><%= p.nationwide ? 'Nationwide' : 'DC Metro' %></span><br/>
            <%= link_to 'View Summary', reference_plan_summary_employers_employer_profile_plan_years_path(ref_plan_id: p.id, hios_id: p.hios_id, coverage_kind: p.coverage_kind), remote: 'true', class: "view-summary fourteen" %>
          </div>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/employers/plan_years/plan_selection/_metal_level.erb
  <% @plans.each do |p| %>
    <div class="col-xs-3">
      <div clas="col-xs-12 reference-plan">
        <div class="col-xs-3">
  <%= radio_button "plan_year[benefit_groups_attributes][0]", :reference_plan_id, p.id %>
  <%= label_tag :reference_plan_id, "" %>
</div>
<div clas="col-xs-9">
  <%= p.name %>
  <%= p.active_year %>
  <%= p.market %>
  <%= p.metal_level %>
  <%= p.plan_type %>
  <%= p.deductible %>
  <%= p.family_deductible %>


  </div>

  </div>
</div>
      <% end %>

app/views/employers/plan_years/plan_selection/_offered_plan.html.erb
<div class="panel benefitgroup col-xs-12">
  <section class="col-xs-6">
    <header class="row">
      <h5 style="color: #69A30D; font-size: 18px;"><%= @plan.name %></h5>
    </header>
  </section>
  <section class="col-xs-6">
  </section>
  <h2></h2>
  <table>
    <tr>
      <th>
        <header>Type</header>
      </th>
      <th>
        <header>Carrier</header>
      </th>
      <th>
        <header>Metal Level</header>
      </th>
      <th>
        <header>Network</header>
      </th>
    </tr>
    <tr>
      <td>
        <p><%= @plan.plan_type.upcase %></p>
      </td>
      <td>
        <p><%= @plan.carrier_profile.legal_name %></p>
      </td>
      <td>
        <p>
          <%= @plan.metal_level.humanize %>
        </p>
      </td>
      <td style="padding-left: 0;">
        <p style="text-transform: capitalize;">
          <%= @plan.nationwide ? 'Nationwide' : 'DC Metro' %>
        </p>
      </td>

    </tr>
  </table>
  <div class="col-xs-12 row plan-details">
    <hr>
    <div class="col-xs-4 row">
      <span>Your Estimated Monthly Cost</span>
      <h2 class="employer-monthly-cost"></h2>
    </div>
    <div class="col-xs-8">
      <table>
        <tr>
          <th></th>
          <th>Min</th>
          <th>Max</th>
        </tr>
        <tr>
          <td>Estimated monthly cost including all roster employees</td>
          <td class="employee-monthly-cost-min"></td>
          <td class="employee-monthly-cost-max" style="padding-left: 0;"></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/employers/plan_years/plan_selection/_plan_details.html.erb
<div class="row">
  <br/><br/>

<div class="col-xs-6">
  <h1>Your Reference Plan</h1>
</div>

<div id="employer_cost_info_btn" class="col-xs-6" style="padding-top: 10px;">
  <div class="btn btn-default btn-right pull-right" style="margin-right: 0;">
    Employee Detail Costs
  </div>
  <%= link_to "Employee Costs", employee_costs_employers_employer_profile_plan_years_path(@employer_profile), id: "employee_costs_link", class: "hidden" %>
</div>
</div>
<%= render "employers/plan_years/employee_costs_modal" %>

<div class="panel benefitgroup col-xs-12 health referenceplan">
  <section class="col-xs-6">
    <header class="row">
      <h5 style="color: #69A30D; font-size: 18px;"><strong><%= @plan.name %></strong></h5>
    </header>
  </section>
  <section class="col-xs-6">
    <h4 class="change-dental-reference-plan pull-right" style="display: none;">Change Reference Plan?</h4>
    <% render partial: "employers/plan_years/dental_reference_plans_options_modal" %>
  </section>
  <h2></h2>
  <table>
    <tr>
      <th>
        <header>Type</header>
      </th>
      <th>
        <header>Carrier</header>
      </th>
      <th>
        <header>Metal Level</header>
      </th>
      <th>
        <header>Network</header>
      </th>
    </tr>
    <tr>
      <td>
        <p><%= @plan.plan_type.try(:upcase) %></p>
      </td>
      <td>
        <p><%= @plan.carrier_profile.legal_name %></p>
      </td>
      <td>
        <p>
          <%= display_dental_metal_level @plan %>
        </p>
      </td>
      <td style="padding-left: 0;">
        <p style="text-transform: capitalize;">
          <%= @plan.nationwide ? 'Nationwide' : 'DC Metro' %></span>
        </p>
      </td>

    </tr>
  </table>
  <div class="col-xs-12 row plan-details">
    <hr>
    <div class="col-xs-4 row">
      <span>Your Estimated Monthly Cost</span>
      <h2 class="employer-monthly-cost"></h2>
    </div>
    <div class="col-xs-8">
      <table>
        <tr>
          <th></th>
          <th>Min</th>
          <th>Max</th>
        </tr>
        <tr>
          <td>Estimated monthly cost including all roster employees</td>
          <td class="employee-monthly-cost-min"></td>
          <td class="employee-monthly-cost-max" style="padding-left: 0;"></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="dental-config-links" style="display: none;">
  <br class="clear"/>
  <br/>
  <h4 class="dental-config-reference-selection">
    Configure which plans you're offering your employees
  </h4>
  <% if @is_edit == 'true' && calc_offered == true %>
  <h4 class="dental-view-summary">
    <%= link_to 'View Plan Summary', reference_plan_summary_employers_employer_profile_plan_years_path(ref_plan_id: @plan.id, hios_id: @plan.hios_id, coverage_kind: @plan.coverage_kind), remote: true %>
  </h4>
  <h4 class="health-view-summary">
    <%= link_to 'View Plan Summary', reference_plan_summary_employers_employer_profile_plan_years_path(ref_plan_id: @plan.id, hios_id: @plan.hios_id, coverage_kind: @plan.coverage_kind), remote: true %>
  </h4>
  <% else %>
  <h4 class="dental-view-summary">
    <%= link_to 'View Plan Summary', 'temp', remote: true %>
  </h4>
  <h4 class="health-view-summary">
    <%= link_to 'View Plan Summary', 'temp', remote: true %>
  </h4>
  <% end %>
  <span></span>
</div>

app/views/employers/plan_years/plan_selection/_single_carriers.html.erb
<% if @single_plan.present? %>
<br><br>
<h4>Let your plan participants choose any plan they would like.<br/>It will not cost you more to let them choose.</h4>
<br/><br/>
<% end %>
<% @plans.each do |p| %>
<div class="col-xs-4">
  <div class="col-xs-12 reference-plan">
    <div class="col-xs-2">

      <%= radio_button "#{@location_id}", :reference_plan_id, p.id %>
      <%= label_tag "#{@location_id}_reference_plan_id" do %>
      <i class="fa fa-circle-o"></i>
      <i class="fa fa-dot-circle-o"></i>
      <% end %>
    </div>

    <div class="col-xs-10">
      <div class="panel row">
        <div class="panel-heading">
          <h3><%= p.name %></h3>
        </div>
        <div class="panel-body">
          <span class="plan-label">Type: </span><span><%= p.plan_type %></span><br>
          <span class="plan-label">Carrier: </span><span><%= @carriers_cache[p.carrier_profile_id] %></span><br>
          <span class="plan-label">Level: </span><span><%= p.metal_level %></span><br>
          <span class="plan-label">Network: </span><span><%= p.nationwide ? 'Nationwide' : 'DC Metro' %></span><br/>
          <%= link_to 'View Summary', reference_plan_summary_employers_employer_profile_plan_years_path(ref_plan_id: p.id, hios_id: p.hios_id, coverage_kind: p.coverage_kind), remote: 'true', class: "view-summary fourteen" %>
        </div>
      </div>

    </div>
  </div>
</div>
<% end %>

app/views/employers/plan_years/plan_selection/_single_plan.html.erb
  <% @plans.each do |p| %>
    <div class="col-xs-3">
      <div clas="col-xs-12 reference-plan">
        <div class="col-xs-3">
  <%= radio_button :reference_plan_id, p.id %>
  <%= label_tag :reference_plan_id %>
</div>
<div clas="col-xs-9">
  <%= p.name %>
  <%= p.active_year %>
  <%= p.market %>
  <%= p.metal_level %>
  <%= p.plan_type %>
  <%= p.deductible %>
  <%= p.family_deductible %>


  </div>

  </div>
</div>
      <% end %>