config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => 'users/sessions' }

  get 'check_time_until_logout' => 'session_timeout#check_time_until_logout', :constraints => { :only_ajax => true }
  get 'reset_user_clock' => 'session_timeout#reset_user_clock', :constraints => { :only_ajax => true }

  match "hbx_admin/update_aptc_csr" => "hbx_admin#update_aptc_csr", as: :update_aptc_csr, via: [:get, :post]
  match "hbx_admin/edit_aptc_csr" => "hbx_admin#edit_aptc_csr", as: :edit_aptc_csr, via: [:get, :post], defaults: { format: 'js' }
  match "hbx_admin/calculate_aptc_csr" => "hbx_admin#calculate_aptc_csr", as: :calculate_aptc_csr, via: :get
  post 'show_hints' => 'welcome#show_hints', :constraints => { :only_ajax => true }

  namespace :users do
    resources :orphans, only: [:index, :show, :destroy]
  end
  
  resources :users do
    member do
      get :reset_password, :lockable, :confirm_lock, :login_history, :change_username_and_email, :edit
      put :confirm_reset_password, :confirm_change_username_and_email, :update
      post :unlock, :change_password
    end
  end

  resources :saml, only: [] do
    collection do
      post :login
      get :logout
      get :navigate_to_assistance
    end
  end

  get 'payment_transactions/generate_saml_response', to: 'payment_transactions#generate_saml_response'

  namespace :exchanges do

    resources :inboxes, only: [:show, :destroy]
    resources :announcements, only: [:index, :create, :destroy] do
      get :dismiss, on: :collection
    end
    resources :agents_inboxes, only: [:show, :destroy]

    resources :residents, only: [:create, :edit, :update] do
      get :search, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :begin_resident_enrollment, on: :collection
      get :resume_resident_enrollment, on: :collection
      get :ridp_bypass, on: :collection
      get :find_sep, on: :collection
    end

    resources :hbx_profiles do
      root 'hbx_profiles#show'

      collection do
        get :family_index
        get :family_index_dt
        get :outstanding_verification_dt
        post :families_index_datatable
        get :employer_index
        get :employer_poc
        post :employer_poc_datatable
        get :employer_invoice
        post :employer_invoice_datatable
        post :generate_invoice
        post :disable_ssn_requirement
        get :broker_agency_index
        get :general_agency_index
        get :issuer_index
        get :product_index
        get :configuration
        post :set_date
        post :update_setting
        get :staff_index
        get :assister_index
        get :request_help
        get :aptc_csr_family_index
        get :binder_index
        get :binder_index_datatable
        post :binder_paid
        get :cancel_enrollment
        post :update_cancel_enrollment
        get :terminate_enrollment
        post :update_terminate_enrollment
        post :add_new_sep
        get :update_effective_date
        get :calculate_sep_dates
        get :add_sep_form
        get :hide_form
        get :show_sep_history
        get :get_user_info
        get :identity_verification
        post :identity_verification_datatable
        get :user_account_index
        get :new_eligibility
      end

      member do
        post :transmit_group_xml
        get :transmit_group_xml
        get :home
        get :inbox
      end

      resources :hbx_staff_roles do
      end
    end

    resources :employer_applications do
      put :terminate
      put :cancel
      put :reinstate
    end

    resources :agents do
      collection do
        get :home
        get :begin_consumer_enrollment
        get :begin_employee_enrollment
        get :resume_enrollment
        get :show
      end
      member do
        get :inbox
      end
    end

    resources :broker_applicants

  end

  namespace :insured do
    get 'verification_documents/upload', to: 'verification_documents#upload'
    post 'verification_documents/upload', to: 'verification_documents#upload'
    get 'verification_documents/download/:key', to: 'verification_documents#download'
    get 'paper_applications/upload', to: 'paper_applications#upload'
    post 'paper_applications/upload', to: 'paper_applications#upload'
    get 'paper_applications/download/:key', to: 'paper_applications#download'
    get 'ridp_documents/upload', to: 'ridp_documents#upload'
    post 'ridp_documents/upload', to: 'ridp_documents#upload'
    get 'ridp_documents/download/:key', to: 'ridp_documents#download'
    resources :ridp_documents, only: [:destroy]

    resources :plan_shoppings, :only => [:show] do
      member do
        get 'plans'
        get 'receipt'
        get 'print_waiver'
        post 'checkout'
        get 'thankyou'
        post 'waive'
        post 'terminate'
        post 'set_elected_aptc'
        get 'plan_selection_callback'
      end
    end

    resources :interactive_identity_verifications, only: [:create, :new, :update] do
      collection do
        get 'failed_validation'
        get 'service_unavailable'
      end
    end

    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :families, only: [:show] do
      get 'new'
      member do
        delete 'delete_consumer_broker'
        get 'generate_out_of_pocket_url'
      end

      collection do
        get 'home'
        get 'manage_family'
        get 'personal'
        get 'inbox'
        get 'brokers'
        get 'verification'
        get 'upload_application'
        get 'document_upload'
        get 'find_sep'
        post 'record_sep'
        get 'check_qle_date'
        get 'check_move_reason'
        get 'check_insurance_reason'
        get 'check_marriage_reason'
        get 'purchase'
        get 'family'
        get 'upload_notice_form'
        post 'upload_notice'
        get 'transition_family_members'
        post 'transition_family_members_update'
      end

      resources :people do
        collection do
          get 'search'
        end
      end
    end

    resources :consumer_role, controller: 'consumer_roles', only: [:create, :edit, :update] do
      get :ssn_taken, on: :collection
      get :search, on: :collection
      get :privacy, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :ridp_agreement, on: :collection
      post :update_application_type
      get :upload_ridp_document, on: :collection
      get :immigration_document_options, on: :collection
    end

    resources :employee, :controller=>"employee_roles", only: [:create, :edit, :update, :show] do
      collection do
        get 'new_message_to_broker'
        post 'send_message_to_broker'
        post :match
        get 'search'
        get 'privacy'
        get 'welcome'
      end
    end

    root 'families#home'

    resources :family_members do
      get :resident_index, on: :collection
      get :new_resident_dependent, on: :collection
      get :edit_resident_dependent, on: :member
      get :show_resident_dependent, on: :member
    end

    resources :group_selections, controller: "group_selection", only: [:new, :create] do
      collection do
        post :terminate
        get :terminate_selection
        get :terminate_confirm
      end
    end

  end

  namespace :employers do
    post 'search', to: 'employers#search'
    root 'employer_profiles#new'

    resources :premium_statements, :only => [:show]

    resources :employer_staff_roles, :only => [:create, :destroy] do
      member do
        get :approve
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'match'
      end
    end
    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :employer_profiles do
      get 'new'
      get 'my_account'
      get 'show_profile'
      get 'link_from_quote'
      get 'consumer_override'
      get 'export_census_employees'
      get 'bulk_employee_upload_form'
      post 'bulk_employee_upload'
      member do
        get "download_invoice"
        post 'generate_checkbook_urls'
      end
      collection do
        get 'welcome'
        get 'search'
        post 'match'
        get 'inbox'
      end
      resources :plan_years do
        get 'reference_plans'
        get 'dental_reference_plans'
        get 'generate_dental_carriers_and_plans'
        get 'plan_details' => 'plan_years#plan_details', on: :collection
        get 'recommend_dates', on: :collection
        get 'reference_plan_options', on: :collection
        post 'revert'
        post 'publish'
        post 'force_publish'
        get 'search_reference_plan', on: :collection
        post 'make_default_benefit_group'
        post 'delete_benefit_group'
        get 'calc_employer_contributions', on: :collection
        get 'calc_offered_plan_contributions', on: :collection
        get 'employee_costs', on: :collection
        get 'reference_plan_summary', on: :collection

      end

      resources :broker_agency, only: [:index, :show, :create] do
        collection do
          get :active_broker
        end
        get :terminate
      end

      resources :census_employees, only: [:new, :create, :edit, :update, :show] do
        get :delink
        get :terminate
        get :rehire
        get :cobra
        get :cobra_reinstate
        get :benefit_group, on: :member
      end
    end
  end

  match 'broker_registration', to: 'broker_agencies/broker_roles#new_broker_agency', via: [:get]

  namespace :carriers do
    resources :carrier_profiles do
    end
  end

  namespace :broker_agencies do
    root 'profiles#new'
    resources :inboxes, only: [:new, :create, :show, :destroy] do
      get :msg_to_portal
    end
    resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
      get :inbox

      collection do
        get :family_index
        get :employers

app/models/access_policies/employer_profile.rb
module AccessPolicies
  class EmployerProfile
    attr_accessor :user

    def initialize(user)
      @user = user
    end

    def authorize_show(employer, controller)
      return(true) if user.has_hbx_staff_role? || is_broker_for_employer?(employer.id) || is_general_agency_staff_for_employer?(employer.id)
      person = user.person

      if person.employer_staff_roles.active.length > 0
        ep_ids = user.person.employer_staff_roles.map(&:employer_profile_id).map(&:to_s)
        if !ep_ids.include?(employer.id.to_s)
          controller.redirect_to_first_allowed
        end
        return true
      end
      controller.redirect_to_new
    end

    def authorize_index(broker_agency_id, controller)
      return(true) if user.has_hbx_staff_role?
      if user.has_broker_role? || user.has_broker_agency_staff_role?
        if !broker_agency_id.blank?
          return
        end
      end
      controller.redirect_to_new
    end

    def is_broker_for_employer?(employer_id)
      person = user.person
      return false unless person.broker_role || person.broker_agency_staff_roles.present?
      if person.broker_role
        employers = ::EmployerProfile.find_by_writing_agent(person.broker_role)
      else
        broker_agency_profiles = person.broker_agency_staff_roles.map {|role| ::BrokerAgencyProfile.find(role.broker_agency_profile_id) }
        employers = broker_agency_profiles.map { |bap| ::EmployerProfile.find_by_broker_agency_profile(bap) }.flatten
      end
      employers.map(&:id).map(&:to_s).include?(employer_id.to_s)
    end

    def authorize_edit(employer_profile, controller)
      return true if @user.has_hbx_staff_role? || is_broker_for_employer?(employer_profile.id) || is_general_agency_staff_for_employer?(employer_profile.id)
      return true if Person.staff_for_employer(employer_profile).include?(@user.person)
      controller.redirect_to_new and return
    end

    def is_general_agency_staff_for_employer?(employer_id)
      person = user.person
      if person.general_agency_staff_roles.present?
        person.general_agency_staff_roles.last.general_agency_profile.employer_clients.map(&:_id).include?(employer_id) rescue false
      else
        false
      end
    end
  end
end

app/models/forms/employer_profile.rb
require 'date'
module Forms
  class EmployerProfile  < ::Forms::OrganizationSignup
    attr_reader :employer_profile
    attr_accessor :email
    attr_accessor :area_code
    attr_accessor :number
    attr_accessor :extension
    class OrganizationAlreadyMatched < StandardError; end

    def check_existing_organization
      claimed = false
      existing_org = Organization.where(:fein => fein).first
      if existing_org.present?
        if existing_org.employer_profile.present?
          if (Person.where({"employer_staff_roles.employer_profile_id" => existing_org.employer_profile._id}).any?)
            claimed = true
          end
        end
      end
      [existing_org, claimed]
    end

    def create_employer_staff_role(current_user, employer_profile, existing_company)
      person.user = current_user
      employer_ids = person.employer_staff_roles.map(&:employer_profile_id)
      if employer_ids.include? employer_profile.id
        pending = false
      else
        pending = existing_company && Person.staff_for_employer(employer_profile).detect{|person|person.user_id}
        role_state = pending ? 'is_applicant' : 'is_active' 
        person.employer_staff_roles << EmployerStaffRole.new(person: person, :employer_profile_id => employer_profile.id, is_owner: true, aasm_state: role_state)
      end
      current_user.roles << "employer_staff" unless current_user.roles.include?("employer_staff")
      current_user.save!
      person.save!
      pending
    end

    def save(current_user, employer_profile_id)
      return false unless valid?
      begin
        match_or_create_person(current_user)
        person.save!
        person.contact_info(email, area_code, number, extension) if email
      rescue TooManyMatchingPeople
        errors.add(:base, "too many people match the criteria provided for your identity.  Please contact HBX.")
        return false
      rescue PersonAlreadyMatched
        errors.add(:base, "a person matching the provided personal information has already been claimed by another user.  Please contact HBX.")
        return false
      end
      return false if person.errors.present?
      existing_org, claimed = check_existing_organization
      if existing_org
        update_organization(existing_org) unless claimed
        @employer_profile = existing_org.employer_profile
      else
        org = create_new_organization
        org.save!
        @employer_profile = org.employer_profile
      end
      pending = create_employer_staff_role(current_user, @employer_profile, claimed)
      [true, pending]
    end

    def create_new_organization
      Organization.create!(
        :fein => fein,
        :legal_name => legal_name,
        :dba => dba,
        :employer_profile => ::EmployerProfile.new({
          :entity_kind => entity_kind,
          :contact_method => contact_method
        }),
        :office_locations => office_locations
      )
    end

    def update_organization(org)
      if !org.employer_profile.present?
        org.create_employer_profile({:entity_kind => entity_kind})
        org.save!
      end
    end

  end
end

app/views/employers/employer_profiles/my_account/_billing.html.erb
<div class="billing-tab">
  <h1 class="darkblue no-buffer">Invoices</h1>
  <%= render partial: "employers/employer_profiles/employer_invoices_table" %>
  <br/>
  <h1 class="darkblue no-buffer">Billing</h1>
  <h4 class="starter">
    <%= Settings.site.short_name %>
    will mail you a monthly invoice at the beginning of each month. The invoice will include charges for the next month's premium payments, as well as any adjustments from previous months. You will make one premium payment each month, regardless of
    whether you offer your employees health coverage from more than one health insurance company or you offer dental coverage to your employees.
  </h4>
  <h4>Your
    <%= Settings.site.short_name %>
    account number:
    <strong><%= "#{@employer_profile.hbx_id}".upcase %></strong>
  </h4>
  <h3><%= Settings.site.short_name %>
    offers multiple payment options including:</h3>
  <h4>
    <ol>
      <li>Pay Online -
        <%= link_to 'How to Pay Online', asset_path("pdf/employers_paying_your_premiums_online.pdf") , target: "_blank"%></li>
      <br/>
      <li>Pay by Phone
        <div class="row col-md-offset-1">
          855-532-LINK, select "Small Business Employer" then "Make a Payment"</li>
        <br/>
        <li>Pay by Mail
          <div class="row col-md-offset-1">
            <%= Settings.site.short_name %></div>
          <div class="row col-md-offset-1">
            PO Box 97022</div>
          <div class="row col-md-offset-1">
            Washington, DC 20090</div>
        </li>
      </h4>
    </ol>
    <h4>**Please include your account number on your check.</h4>
    <h4>Check that your mailing address is up to date - click on Update Business Info.</h4>
  </div>
</div>

app/views/employers/employer_profiles/my_account/_employees_by_status.html.erb
<% if @search || params[:employee_search] %>
<% if @census_employees.present? %>
<% else %>
<h4>No results found</h4>
<% end %>
<% end %>
  <div class="table-responsive">
    <table class="table table-striped table-hover table-sm panel panel-default">
      <thead class="thead-default">
        <tr>
          <th>Employee Name<!-- <i class="fa fa-caret-down"></i>--></th>
          <th>Date of Birth</th>
          <th>Date of Hire</th>
          <th>Employee Account Status</th>
          <th>Benefit Package</th>
          <% if @employer_profile.renewing_plan_year.present? %>
          <th>Renewal Benefit Package</th>
          <% end %>
          <% if ['terminated', 'all'].include?(status) %>
            <th>Termination Date</th>
          <% end %>
          <th>Current Enrollment Status</th>
          <% if @employer_profile.renewing_published_plan_year.present? %>
              <th>Renewal Enrollment Status</th>
          <% end %>
          <th>
            &nbsp;
          </th>
          <th>
            &nbsp;
          </th>
        </tr>
      </thead>
      <tbody>
      <% if @census_employees.present? %>
      <% @census_employees.each do |census_employee| %>
        <tr class="terminated_<%= census_employee.employment_terminated? %> remove_<%= census_employee.id %> top <%= cycle('odd','even')%>">
          <td>
            <%= link_to name_to_listing(census_employee), employers_employer_profile_census_employee_path(@employer_profile.id, census_employee.id, status: status) %>
          </td>
          <td><%= format_date census_employee.dob %></td>
          <td><%= format_date census_employee.hired_on %></td>
          <td style="text-transform: capitalize;"><%= employee_state_format(census_employee.aasm_state, census_employee.employment_terminated_on) %></td>
          <td>
          <% if census_employee.active_benefit_group_assignment.present? %>
            <%= census_employee.active_benefit_group_assignment.benefit_group.title.capitalize %>
          <% end %>
          </td>
          <% if @employer_profile.renewing_plan_year.present? %>
          <td>
          <% if census_employee.renewal_benefit_group_assignment.present? %>
            <%= census_employee.renewal_benefit_group_assignment.benefit_group.title.capitalize %>
          <% end %>
          </td>
          <% end %>
          <% if ['terminated', 'all'].include?(status) %>
            <td><%= format_date census_employee.employment_terminated_on %></td>
          <% end %>
          <td><%= enrollment_state(census_employee) %></td>
          <% if @employer_profile.renewing_published_plan_year.present? %>
              <td><%= renewal_enrollment_state(census_employee) %></td>
          <% end %>
          <% if census_employee.aasm_state == 'employment_terminated' %>
            <td class="table-functions">
              <a class="show_confirm btn btn-green-2 <%= pundit_class EmployerProfile, :updateable? %>" id="show_confirm_<%= census_employee.id %>">
                <span class="hidden-xs hidden-sm visible-md visible-lg" onclick="$(this).closest('tr').nextAll('.rehire_<%= census_employee.id %>').toggle();">Rehire</span>
              </a>
            </td>
          <% elsif census_employee.may_terminate_employee_role? %>
            <td class="table-functions">
              <%= link_to raw('<i class="fa fa-pencil fa-lg pull-right" data-toggle="tooltip" title="Edit"></i>'), edit_employers_employer_profile_census_employee_path(@employer_profile, census_employee.id) %>
              <i class="fa fa-trash-o fa-lg pull-right" data-toggle="tooltip" title="Terminate"></i>
            </td>
          <% else %>
            <td class="table-functions"></td>
          <% end %>
          <% if census_employee.can_elect_cobra? || census_employee.may_reinstate_eligibility? %>
            <td class="table-functions">
             <%= cobra_button(census_employee) %>
            </td>
          <% else %>
            <td class="table-functions"></td>
          <% end %>
        </tr>

        <% if census_employee.can_elect_cobra? %>
          <tr class="unbrd cobra_confirm cobra_confirm_<%= census_employee.id %> dn">
            <td class="confirm-terminate-wrapper" colspan="3">
              <span>Employment Termination Date: </span>
              <span><%= format_date census_employee.employment_terminated_on %></span>
            </td>
            <td class="confirm-cobra-wrapper" colspan="4" id="enter-date">
              <%=cobra_effective_date(census_employee) %>
            </td>
            <td colspan="2">
              <a class="btn btn-default cobra_confirm_submit" data-link="<%= employers_employer_profile_census_employee_cobra_path(@employer_profile.id, census_employee.id) %>" href="javascript:;" id="cobra_<%= census_employee.id %>" onclick="EmployerProfile.submitCobraDate('cobra_confirm', '<%= census_employee.id %>')">
                <strong>&nbsp;Submit</strong>
              </a>
            </td>
          </tr>
        <% end %>
        <% if census_employee.may_reinstate_eligibility? %>
         <tr class="unbrd cobra_confirm cobra_reinstate_<%= census_employee.id %> dn">
            <td class="confirm-terminate-wrapper" colspan="3">
              <span>Employment Termination Date: </span>
              <span><%= format_date census_employee.employment_terminated_on %></span>
            </td>
            <td class="confirm-cobra-wrapper" colspan="4" id="enter-date">
              <%=cobra_effective_date(census_employee) %>
            </td>
            <td colspan="2">
              <a class="btn btn-default cobra_confirm_submit" data-link="<%= employers_employer_profile_census_employee_cobra_reinstate_path(@employer_profile.id, census_employee.id) %>" href="javascript:;" id="cobra_<%= census_employee.id %>" onclick="EmployerProfile.submitCobraDate('cobra_reinstate', '<%= census_employee.id %>')">
                <strong>&nbsp;Submit</strong>
              </a>
            </td>
          </tr>
          <%end%>
        <% if census_employee.aasm_state == 'employment_terminated' %>
        <tr class="unbrd  rehire_<%= census_employee.id %> dn">
          <td class="confirm-terminate-wrapper show_confirm_<%= census_employee.id %>" colspan="11" id="enter-date">
            <span><%=image_tag "enter_rehire_date.png", alt: "Enter re-hire date.", width: "200", height: "" %></span>
            <span class="confirm-terminate" style="display:inline;">
              <input class="text-center date-picker" data-date-min="<%= rehire_date_min(census_employee) %>d" placeholder="e.g. 5/1/2015" type="text">
              <a class="rehire_confirm" data-link="<%= employers_employer_profile_census_employee_rehire_path(@employer_profile.id, census_employee.id) %>" href="javascript:;" id="rehire_<%= census_employee.id %>">
                <strong>&nbsp;Submit</strong>
              </a>
            </span>
          </td>
        </tr>
            <tr></tr>
          <% elsif census_employee.may_terminate_employee_role? %>
            <tr class="unbrd  remove_<%= census_employee.id %> dn">
              <td class="confirm-terminate-wrapper show_confirm_<%= census_employee.id %>"  colspan="10"  id="enter-date">
                <div class="confirm-terminate <%=pundit_class EmployerProfile, :updateable?%>">
                  <h5 style="margin-top: 0; margin-bottom: 0;"><strong>Enter termination date to remove <%= name_to_listing(census_employee) %></strong>
                    <br/>
                    <span class="lg fourteen">(termination date must be within the past 60 days)</span>
                  </h5>
                  <div class="pull-right" style="margin-top: 2px;">
                  <i class="fa fa-calendar fa-lg"></i> <input class="text-center date-picker" data-date-min="<%= (census_employee.hired_on - TimeKeeper.date_of_record).to_i + 1 > -60 ? (census_employee.hired_on - TimeKeeper.date_of_record).to_i + 1 : -60 %>d" placeholder="MM/DD/YYYY" type="text">
                  <a class="delete_confirm terminate" data-link="<%= employers_employer_profile_census_employee_terminate_path(@employer_profile.id, census_employee.id) %>" href="javascript:;" id="remove_<%= census_employee.id %>">
                  Terminate Employee
                  </a>
                  <a class="terminate cancel" style="margin-right: 15px;">Cancel</a>
                </div>
                </div>
              </td>
            </tr>
            <% end %>
          <% end %>
          <% end %>
       </tbody>
      </table>
    </div>
  <%= paginate @census_employees, param_name: :pagina, remote: true if params[:page].present? %>
  <div class="row">
    <div class="col-md-9">
      <% if (@total_census_employees_quantity.present? || !params[:page].nil?) && (@total_census_employees_quantity != @census_employees.count) %>
      <%= render 'shared/alph_paginate', url: employers_employer_profile_path(@employer_profile), alphs: @page_alphabets, remote: true, status: status, full_index_url: employers_employer_profile_path(@employer_profile, status: status, employee_search: params[:employee_search]) %>
      <% end %>
    </div>
    <div class="col-md-3 text-right content-bottom">
      <h4><%= "#{@census_employees.count} out of #{@total_census_employees_quantity}" if @total_census_employees_quantity.present? %></h4>
    </div>
  </div>
</div>

app/views/employers/employer_profiles/my_account/_employer.html.erb
_employer.html.erb

app/views/employers/employer_profiles/my_account/_employer_welcome.html.erb
<div class="module employer-welcome col-xs-12">
  <div class="row">
    <h4 class="dir">
      It's time to set up your Health Benefits Program. You can either get help from a Broker, or set up your Health Benefits Program yourself. Choose the path that's right for you.
    </h4>
  </div>
  <br/>
  <% unless @employer_profile.broker_agency_profile.present?  %>
    <div class="left-icon-section section">
      <div class="row">
        <div class="col-xs-1">
          <div class="row">
            <%= image_tag('ui/expertgreen_50.png') %>
          </div>
        </div>

        <div class="col-xs-11">
          <h3 class="no-buffer">
            Get Help From a Broker
          </h3>
          <h4>
            You may want to select a Broker as your personal advocate and trusted adviser, who at no cost to you, can help you set up and administer your Health Benefits Program. If you'd like to select a Broker, we suggest doing so first.
            <%= link_to '#', class: 'view-more' do %>
            View More
            <i class="fa fa-chevron-down"></i>
            <% end %>
          </h4>
          <div class="empty-box x-right col-xs-12 dn">
            <div class="col-xs-12">
              <div class="row">
                Select
                <%= link_to "\"Brokers\"", employers_employer_profile_path(@employer_profile, tab: 'brokers') %>
                on the blue menu to the left and follow the instructions. Once you've confirmed your selection, you can logout. Your Broker will be in touch shortly and will help you do everything else.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="left-icon-section section">
    <div class="row">
      <div class="col-xs-1">
        <div class="row">
          <%= image_tag('ui/gearsgreen_50.png') %>
        </div>
      </div>
      <div class="col-xs-11">
        <h3 class="no-buffer">
          Set Up Your Health Benefits Program Yourself
        </h3>
        <h4>
          If you want to set up your Health Benefits Program yourself, we'll walk you through it step-by-step.
          <%= link_to '#', class: 'view-more' do %>
          View More
          <i class="fa fa-chevron-down"></i>
          <% end %>
        </h4>
        <div class="empty-box close-right col-xs-12 dn">
          <div class="col-xs-12">
            <div class="row">
              To get started, select '<%= link_to "\"Employees\"", employers_employer_profile_path(@employer_profile, tab: 'employees') %>' on the blue menu to the left and follow the instructions to add your employee roster. Then we'll help you create your plan(s), assign employees to your plan(s) and publish your plan(s) for open enrollment.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="left-icon-section empty-box important row section">
    <div class="vertically-aligned-row">
      <div class="col-xs-1">
        <i class="fa fa-flag fa-2x"></i>
      </div>
      <div class="col-xs-9">
        <span>
          <strong>Important:
          </strong>You'll want to enter your employee roster first before selecting your Benefits so that you'll be able to see cost data when you select your Benefits.
        </span>
        <div class="icon-left-download">
          <%= link_to "https://dchealthlink.com/sites/default/files/v2/forms/Initial-Employers-Creating-an-Account.pdf", target: '_blank' do %>
            <i class="fa fa-download">
            </i>
            Download Step-by-Step Instructions for New Employers
          <% end %>
        </div>
      </div>
      <div class="col-xs-2 pdf-image full-width">
        <%= link_to 'https://dchealthlink.com/sites/default/files/v2/forms/Initial-Employers-Creating-an-Account.pdf', target: '_blank' do %>
        <%= image_tag('images/guidanceforsmallbusinessowners_214.jpg', class: 'pull-right') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/employers/employer_profiles/my_account/_families.html.erb
<div class='col-md-12' id='families'>
  <h4> Families </h4>
  <table class="table table-condensed" style="opacity: 1;">
    <thead>
      <tr>
        <th colspan="6">Primary Applicant</th>
      </tr>
      <tr>
        <th>Employee Name</th>
        <th>SSN</th>
        <th>DOB</th>
        <th>HBX ID</th>
        <th>Family Ct</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <% person = employee.person %>
        <% if person.has_active_employee_role? %>
          <tr>
            <td> <%= link_to person.full_name, employers_employer_profile_consumer_override_path(:person_id=> person.id, employer_profile_id: @employer_profile.id)%>  </td>
            <td> <%= number_to_obscured_ssn person.ssn %> </td>
            <td> <%= format_date person.dob%></td>
            <td> <%= person.hbx_id %> </td>
            <td> <%= person.primary_family.present? ? person.primary_family.active_family_members.size : 0 %> </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>