config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => 'users/sessions' }

  get 'check_time_until_logout' => 'session_timeout#check_time_until_logout', :constraints => { :only_ajax => true }
  get 'reset_user_clock' => 'session_timeout#reset_user_clock', :constraints => { :only_ajax => true }

  match "hbx_admin/update_aptc_csr" => "hbx_admin#update_aptc_csr", as: :update_aptc_csr, via: [:get, :post]
  match "hbx_admin/edit_aptc_csr" => "hbx_admin#edit_aptc_csr", as: :edit_aptc_csr, via: [:get, :post], defaults: { format: 'js' }
  match "hbx_admin/calculate_aptc_csr" => "hbx_admin#calculate_aptc_csr", as: :calculate_aptc_csr, via: :get
  post 'show_hints' => 'welcome#show_hints', :constraints => { :only_ajax => true }

  namespace :users do
    resources :orphans, only: [:index, :show, :destroy]
  end
  
  resources :users do
    member do
      get :reset_password, :lockable, :confirm_lock, :login_history, :change_username_and_email, :edit
      put :confirm_reset_password, :confirm_change_username_and_email, :update
      post :unlock, :change_password
    end
  end

  resources :saml, only: [] do
    collection do
      post :login
      get :logout
      get :navigate_to_assistance
    end
  end

  get 'payment_transactions/generate_saml_response', to: 'payment_transactions#generate_saml_response'

  namespace :exchanges do

    resources :inboxes, only: [:show, :destroy]
    resources :announcements, only: [:index, :create, :destroy] do
      get :dismiss, on: :collection
    end
    resources :agents_inboxes, only: [:show, :destroy]

    resources :residents, only: [:create, :edit, :update] do
      get :search, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :begin_resident_enrollment, on: :collection
      get :resume_resident_enrollment, on: :collection
      get :ridp_bypass, on: :collection
      get :find_sep, on: :collection
    end

    resources :hbx_profiles do
      root 'hbx_profiles#show'

      collection do
        get :family_index
        get :family_index_dt
        get :outstanding_verification_dt
        post :families_index_datatable
        get :employer_index
        get :employer_poc
        post :employer_poc_datatable
        get :employer_invoice
        post :employer_invoice_datatable
        post :generate_invoice
        post :disable_ssn_requirement
        get :broker_agency_index
        get :general_agency_index
        get :issuer_index
        get :product_index
        get :configuration
        post :set_date
        post :update_setting
        get :staff_index
        get :assister_index
        get :request_help
        get :aptc_csr_family_index
        get :binder_index
        get :binder_index_datatable
        post :binder_paid
        get :cancel_enrollment
        post :update_cancel_enrollment
        get :terminate_enrollment
        post :update_terminate_enrollment
        post :add_new_sep
        get :update_effective_date
        get :calculate_sep_dates
        get :add_sep_form
        get :hide_form
        get :show_sep_history
        get :get_user_info
        get :identity_verification
        post :identity_verification_datatable
        get :user_account_index
        get :new_eligibility
      end

      member do
        post :transmit_group_xml
        get :transmit_group_xml
        get :home
        get :inbox
      end

      resources :hbx_staff_roles do
      end
    end

    resources :employer_applications do
      put :terminate
      put :cancel
      put :reinstate
    end

    resources :agents do
      collection do
        get :home
        get :begin_consumer_enrollment
        get :begin_employee_enrollment
        get :resume_enrollment
        get :show
      end
      member do
        get :inbox
      end
    end

    resources :broker_applicants

  end

  namespace :insured do
    get 'verification_documents/upload', to: 'verification_documents#upload'
    post 'verification_documents/upload', to: 'verification_documents#upload'
    get 'verification_documents/download/:key', to: 'verification_documents#download'
    get 'paper_applications/upload', to: 'paper_applications#upload'
    post 'paper_applications/upload', to: 'paper_applications#upload'
    get 'paper_applications/download/:key', to: 'paper_applications#download'
    get 'ridp_documents/upload', to: 'ridp_documents#upload'
    post 'ridp_documents/upload', to: 'ridp_documents#upload'
    get 'ridp_documents/download/:key', to: 'ridp_documents#download'
    resources :ridp_documents, only: [:destroy]

    resources :plan_shoppings, :only => [:show] do
      member do
        get 'plans'
        get 'receipt'
        get 'print_waiver'
        post 'checkout'
        get 'thankyou'
        post 'waive'
        post 'terminate'
        post 'set_elected_aptc'
        get 'plan_selection_callback'
      end
    end

    resources :interactive_identity_verifications, only: [:create, :new, :update] do
      collection do
        get 'failed_validation'
        get 'service_unavailable'
      end
    end

    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :families, only: [:show] do
      get 'new'
      member do
        delete 'delete_consumer_broker'
        get 'generate_out_of_pocket_url'
      end

      collection do
        get 'home'
        get 'manage_family'
        get 'personal'
        get 'inbox'
        get 'brokers'
        get 'verification'
        get 'upload_application'
        get 'document_upload'
        get 'find_sep'
        post 'record_sep'
        get 'check_qle_date'
        get 'check_move_reason'
        get 'check_insurance_reason'
        get 'check_marriage_reason'
        get 'purchase'
        get 'family'
        get 'upload_notice_form'
        post 'upload_notice'
        get 'transition_family_members'
        post 'transition_family_members_update'
      end

      resources :people do
        collection do
          get 'search'
        end
      end
    end

    resources :consumer_role, controller: 'consumer_roles', only: [:create, :edit, :update] do
      get :ssn_taken, on: :collection
      get :search, on: :collection
      get :privacy, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :ridp_agreement, on: :collection
      post :update_application_type
      get :upload_ridp_document, on: :collection
      get :immigration_document_options, on: :collection
    end

    resources :employee, :controller=>"employee_roles", only: [:create, :edit, :update, :show] do
      collection do
        get 'new_message_to_broker'
        post 'send_message_to_broker'
        post :match
        get 'search'
        get 'privacy'
        get 'welcome'
      end
    end

    root 'families#home'

    resources :family_members do
      get :resident_index, on: :collection
      get :new_resident_dependent, on: :collection
      get :edit_resident_dependent, on: :member
      get :show_resident_dependent, on: :member
    end

    resources :group_selections, controller: "group_selection", only: [:new, :create] do
      collection do
        post :terminate
        get :terminate_selection
        get :terminate_confirm
      end
    end

  end

  namespace :employers do
    post 'search', to: 'employers#search'
    root 'employer_profiles#new'

    resources :premium_statements, :only => [:show]

    resources :employer_staff_roles, :only => [:create, :destroy] do
      member do
        get :approve
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'match'
      end
    end
    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :employer_profiles do
      get 'new'
      get 'my_account'
      get 'show_profile'
      get 'link_from_quote'
      get 'consumer_override'
      get 'export_census_employees'
      get 'bulk_employee_upload_form'
      post 'bulk_employee_upload'
      member do
        get "download_invoice"
        post 'generate_checkbook_urls'
      end
      collection do
        get 'welcome'
        get 'search'
        post 'match'
        get 'inbox'
      end
      resources :plan_years do
        get 'reference_plans'
        get 'dental_reference_plans'
        get 'generate_dental_carriers_and_plans'
        get 'plan_details' => 'plan_years#plan_details', on: :collection
        get 'recommend_dates', on: :collection
        get 'reference_plan_options', on: :collection
        post 'revert'
        post 'publish'
        post 'force_publish'
        get 'search_reference_plan', on: :collection
        post 'make_default_benefit_group'
        post 'delete_benefit_group'
        get 'calc_employer_contributions', on: :collection
        get 'calc_offered_plan_contributions', on: :collection
        get 'employee_costs', on: :collection
        get 'reference_plan_summary', on: :collection

      end

      resources :broker_agency, only: [:index, :show, :create] do
        collection do
          get :active_broker
        end
        get :terminate
      end

      resources :census_employees, only: [:new, :create, :edit, :update, :show] do
        get :delink
        get :terminate
        get :rehire
        get :cobra
        get :cobra_reinstate
        get :benefit_group, on: :member
      end
    end
  end

  match 'broker_registration', to: 'broker_agencies/broker_roles#new_broker_agency', via: [:get]

  namespace :carriers do
    resources :carrier_profiles do
    end
  end

  namespace :broker_agencies do
    root 'profiles#new'
    resources :inboxes, only: [:new, :create, :show, :destroy] do
      get :msg_to_portal
    end
    resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
      get :inbox

      collection do
        get :family_index
        get :employers

app/controllers/broker_agencies/applicants_controller.rb
class BrokerAgencies::ApplicantsController < ApplicationController

  before_action :find_broker_agency_profile
  before_action :check_primary_broker_role
  before_action :find_broker_applicant, only: [:edit, :update]

  def index
    @people = Person.find_all_brokers_or_staff_members_by_agency(@broker_agency_profile).sans_primary_broker(@broker_agency_profile)
    @status = params.permit(:status)[:status] || 'broker_agency_pending'
    @people = Person.brokers_or_agency_staff_with_status(@people, @status) unless @status == 'all'

    @page_alphabets = page_alphabets(@people, "last_name")

    if params[:page].present?
      page_no = cur_page_no(@page_alphabets.first)
      @broker_applicants = @people.where("last_name" => /^#{page_no}/i)
    else
      @broker_applicants = @people.to_a.first(20)
    end

    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    role = @broker_applicant.broker_role
    role = @broker_applicant.broker_agency_staff_roles[0] unless role

    # if params[:person] && params[:person][:broker_role_attributes] && params[:person][:broker_role_attributes][:reason]
    #   broker_role.update_attributes(:reason => params[:person][:broker_role_attributes][:reason])
    # end

    if params['decline']
      role.broker_agency_decline!
      flash[:notice] = "Applicant declined."
    elsif params['terminate']
      role.broker_agency_terminate!
      flash[:notice] = "Applicant terminated."
    else
      role.broker_agency_accept!
      flash[:notice] = "Applicant accepted successfully."
    end

    redirect_to broker_agencies_profile_path(@broker_agency_profile)
  end

  private

  def find_broker_agency_profile
    @broker_agency_profile = BrokerAgencyProfile.find(params[:profile_id])
    if @broker_agency_profile.nil?
      redirect_to broker_agencies_profiles_path(@broker_agency_profile), :flash => { :error => "Something went wrong!!" }
    end
  end

  def find_broker_applicant
    @broker_applicant = Person.find(BSON::ObjectId.from_string(params[:id]))
  end

  def check_primary_broker_role
    return true if current_user.has_hbx_staff_role?

    person = current_user.person
    return true if person.broker_role && person.broker_role.is_primary_broker?

    redirect_to broker_agencies_profiles_path(@broker_agency_profile), :flash => { :error => "You must be a Primary broker" }
  end
end

app/controllers/employers/employers_controller.rb
class Employers::EmployersController < ApplicationController
  def search
    @employers = Organization.where(employer_profile: {:$exists=> true}, legal_name: /^#{params[:q]}/i)
    result=@employers.limit(7).select{|org| Person.where({"employer_staff_roles.employer_profile_id" => org.employer_profile._id}).any?}
    render json: result
  end

  def redirect_to_new
    redirect_to new_employers_employer_profile_path
  end
end

app/controllers/employers/inboxes_controller.rb
class Employers::InboxesController < InboxesController

  def new
    @inbox_to_name = params["to"]
    @inbox_provider_name = 'HBXAdmin'
    super
  end

  def find_inbox_provider
    @inbox_provider = EmployerProfile.find(params["id"])
    @inbox_provider_name = @inbox_provider.legal_name
  end

  def successful_save_path
    exchanges_hbx_profiles_root_path
  end
end

app/helpers/broker_agencies/profiles_helper.rb
module BrokerAgencies::ProfilesHelper
  def fein_display(broker_agency_profile)
    (broker_agency_profile.organization.is_fake_fein? && !current_user.has_broker_agency_staff_role?)|| (broker_agency_profile.organization.is_fake_fein? && current_user.has_hbx_staff_role?) || !broker_agency_profile.organization.is_fake_fein?
  end
end

app/helpers/broker_agencies/quote_helper.rb
module BrokerAgencies::QuoteHelper

  def draft_quote_header(state,quote_name)
    if state == "draft"
      content_tag(:h3, "Review: Publish your #{quote_name}" )+
      content_tag(:span, "Please review the information below before publishing your quote. Once the quote is published, no information can be changed.")
    end
  end

  def display_dental_plan_option_kind(bg)
    kind = bg.dental_plan_option_kind
    if kind == 'single_carrier'
      'Single Carrier'
    else
      'Custom'
    end
  end

  def get_health_cost_comparison(options={})
    @qbg = options[:benefit_id].present? && options[:quote_id].present? ? Quote.find(params[:quote_id]).quote_benefit_groups.find(params[:benefit_id]) : options[:benefit_group]
    @quote_results = Hash.new
    @health_plans = Plan.shop_health_plans @qbg.quote.plan_year
    unless @qbg.nil?
      roster_premiums = @qbg.roster_cost_all_plans
      @roster_elected_plan_bounds = PlanCostDecoratorQuote.elected_plans_cost_bounds(@health_plans,
      @qbg.quote_relationship_benefits, roster_premiums)
      elected_health_plan_ids = options[:plan_ids].present? ? options[:plan_ids] : @qbg.elected_health_plan_ids
      elected_health_plan_ids.each do |plan_id|
        p = @health_plans.detect{|plan| plan.id.to_s == plan_id.to_s}
        detailCost = Array.new
        @qbg.quote_households.each do |hh|
          pcd = PlanCostDecoratorQuote.new(p, hh, @qbg, p)
          detailCost << pcd.get_family_details_hash(@qbg.quote.start_on).sort_by { |m|
           [m[:family_id], -m[:age], -m[:employer_contribution]]
          }
        end
        employer_cost = @qbg.roster_employer_contribution(p,p)
        @quote_results[p.name] = {:detail => detailCost,
          :total_employee_cost => @qbg.roster_employee_cost(p),
          :total_employer_cost => employer_cost,
          plan_id: plan_id,
          buy_up: PlanCostDecoratorQuote.buy_up(employer_cost, p.metal_level, @roster_elected_plan_bounds)
        }
      end
    end
    @quote_results = @quote_results.sort_by { |k, v| v[:total_employer_cost] }.to_h
  end

  def get_dental_cost_comparison(options={})
    @qbg = options[:benefit_id].present? && options[:quote_id].present? ? Quote.find(params[:quote_id]).quote_benefit_groups.find(params[:benefit_id]) : options[:benefit_group]
    @quote_results = Hash.new
    @health_plans = Plan.shop_dental_plans(@qbg.quote.plan_year)
    @roster_elected_plan_bounds = PlanCostDecoratorQuote.elected_plans_cost_bounds(
      @health_plans,
      @qbg.quote_dental_relationship_benefits,
      @qbg.roster_cost_all_plans('dental'))
    elected_dental_plan_ids = options[:plan_ids].present? ? options[:plan_ids] : @qbg.elected_dental_plan_ids
    elected_dental_plan_ids.each do |plan_id|
      p = @health_plans.detect{|plan| plan.id.to_s == plan_id.to_s}
      detailCost = Array.new
      @qbg.quote_households.each do |hh|
        pcd = PlanCostDecoratorQuote.new(p, hh, @qbg, p)
        detailCost << pcd.get_family_details_hash(@qbg.quote.start_on).sort_by { |m| [m[:family_id], -m[:age], -m[:employer_contribution]] }
      end

      employer_cost = @qbg.roster_employer_contribution(p,p)
      @quote_results[p.name] = {:detail => detailCost,
        :total_employee_cost => @qbg.roster_employee_cost(p),
        :total_employer_cost => employer_cost,
        plan_id: plan_id,
      }
    end
    @quote_results = @quote_results.sort_by { |k, v| v[:total_employer_cost] }.to_h
  end

end

app/helpers/employers/broker_agency_helper.rb
module Employers::BrokerAgencyHelper
  def assignment_date(employer_profile)
    employer_profile.active_broker_agency_account.start_on if employer_profile.active_broker_agency_account.present?
  end
end

app/helpers/employers/census_employees_helper.rb
module Employers::CensusEmployeesHelper

end

app/views/employers/broker_agency/_active_broker.html.erb
<div class="no-buffer module" id="active_broker_tab">
  <div class="col-xs-12">
    <div class="row">
      <% if @employer_profile.broker_agency_profile.present? && @broker_agency_accounts[0].writing_agent.present? %>
        <div class="vertically-aligned-row">
          <h1 class="darkblue no-buffer">Brokers</h1>
          <div class="text-right">
            <% if current_user.can_change_broker? %>
              <%= link_to '<i class="fa fa-search" aria-hidden="true"></i> &nbsp;Browse Brokers'.html_safe, "/employers/employer_profiles/#{@employer_profile.id}/broker_agency", remote: true, class: "btn btn-primary", id: 'browse_brokers_link',
                onclick: '$("#brokers-empty").hide(); $("#active_broker_tab").hide(); $("#browse_brokers_link").hide()' %>
            <% else %>
              <%= link_to '<i class="fa fa-search" aria-hidden="true"></i> &nbsp;Browse Brokers'.html_safe, ('javascript:;'), class: "btn btn-primary disabled" %>
            <% end %>
          </div>
        </div>
        <% active_broker = @broker_agency_accounts[0].writing_agent %>
        <div class="panel panel-default module broker employer-broker">
          <div class="panel-heading vertically-aligned-row">
            <div>
              <h3 class="panel-title">
                Active Broker
              </h3>
            </div>
            <div class="text-right">
              <% if (defined?(direct_terminate) ? direct_terminate : false) %>
                <% if @broker_agency_accounts.first.start_on == TimeKeeper.date_of_record %>
                  <% date = TimeKeeper.date_of_record %>
                <% else %>
                  <% date = TimeKeeper.date_of_record - 1.day %>
                <% end %>
                <% if current_user.can_change_broker? %>
                  <%= link_to "Change Broker &nbsp;<i class='fa fa-user-times' aria-hidden='true'></i>".html_safe, ('javascript:;'), class: "btn btn-default", data: {toggle: "modal", target: "#terminate_broker"} %>
                <% else %>
                  <%= link_to "Change Broker &nbsp;<i class='fa fa-user-times' aria-hidden='true'></i>".html_safe, ('javascript:;'), class: "btn btn-default disabled" %>
                <% end %>
              <% else %>
                <% if current_user.can_change_broker? %>
                  <%= link_to 'Change Broker'.html_safe, ('javascript:;'), class: "btn btn-default", id: "show_confirm_#{@employer_profile.broker_agency_profile.id}" %>
                <% else %>
                  <%= link_to 'Change Broker'.html_safe, ('javascript:;'), class: "btn btn-default disabled" %>
                <% end %>
                <table class="table table-wrapper" style="opacity: 1;">
                  <tbody>
                    <tr class="unbrd remove_<%= @employer_profile.broker_agency_profile.id %>">
                      <td class="confirm-terminate-wrapper show_confirm_<%= @employer_profile.broker_agency_profile.id %>" colspan="7" id="enter-date">
                        <div class="confirm-terminate">
                          <input class="text-center date-picker" placeholder="e.g. 5/1/2015" type="text"><br/>
                          <a class="delete_confirm" data-link="<%= employers_employer_profile_broker_agency_terminate_path(@employer_profile.id, @employer_profile.broker_agency_profile.id) %>" href="javascript:;" id="remove_<%= @employer_profile.broker_agency_profile.id %>">
                            <strong>Submit</strong>
                          </a>
                        </div>
                        <%= image_tag "enter_date_termination.png", width: "300", height: "" %>
                      </td>
                    </tr>
                  </tbody>
                </table>
              <% end %>
            </div>
          </div>
          <div class="panel-body">
            <div class="vertically-aligned-row">
              <div>
                <strong>
                  Broker Name:
                </strong>
                <span>
                  <%= active_broker.person.full_name.titleize %>
                </span>
              </div>
              <div>
                <strong>
                  Phone:
                </strong>
                <span>
                  <% if active_broker.phone %>
                  <%= active_broker.phone.to_s %>
                  <% else %>
                  <% end %>
                </span>
              </div>
            </div>
            <div class="vertically-aligned-row">
              <div>
                <strong>
                  Broker Agency:
                </strong>
                <span>
                  <%= @employer_profile.broker_agency_profile.legal_name.titleize %>
                </span>
              </div>
              <div>
                <strong>
                  Email:
                </strong>
                <span>
                  <a href="mailto:<%= active_broker.email.address %>">
                    <%= active_broker.email.address %>
                  </a>
                </span>
              </div>
            </div>
            <div class="vertically-aligned-row">
              <div>
                <strong>
                  Address:
                </strong>
                <span>
                  <% if @employer_profile.broker_agency_profile.organization.office_locations.any? %>
                    <%= @employer_profile.broker_agency_profile.organization.primary_office_location.address.full_address %>
                  <% else %>
                  <% end %>
                </span>
              </div>
              <div></div>
            </div>
            <br/>
            <div class="vertically-aligned-row">
              <div>
                <strong>
                  Accepting New Clients:
                </strong>
                <span>
                  <%= @employer_profile.broker_agency_profile.accept_new_clients? ? 'Yes' : 'No' %>
                </span>
              </div>
              <div>
                <strong>
                  Language:
                </strong>
                <span>
                  <%= @employer_profile.broker_agency_profile.languages %>
                </span>
              </div>
            </div>
            <div class="vertically-aligned-row">
              <div>
                <strong>
                  Weekend/Evening Hours:
                </strong>
                <span>
                  <%= @employer_profile.broker_agency_profile.working_hours? ? 'Yes' : 'No' %>
                </span>
              </div>
              <div>
                <strong>
                  Assignment Date:
                </strong>
                <span>
                  <%= format_date(assignment_date(@employer_profile)) %>
                </span>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    <% if (defined?(direct_terminate) ? direct_terminate : false) %>

    <div class="modal fade" id="terminate_broker" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button class="close" data-dismiss="modal" type="button">&times;</button>
            <h4 class="modal-title">Broker Termination Confirmation</h4>
          </div>
          <div class="modal-body">
            <p>Select 'Terminate' to unhire the selected Broker. They will be terminated effective immediately.</p>
          </div>
          <div class="modal-footer">
            <%= link_to 'Terminate Broker'.html_safe, employers_employer_profile_broker_agency_terminate_path(@employer_profile.id, @employer_profile.broker_agency_profile.id, termination_date: date, direct_terminate: true), class: "btn btn-primary  mtz" %>
            <button class="btn btn-default btn-default" data-dismiss="modal" type="button">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if !@employer_profile.broker_agency_profile.present? %>
    <div class="col-xs-12 col-sm-4 col-md-4">
      <div class="row">
        <% if current_user.can_change_broker? %>
          <%= link_to '<i class="fa fa-search" aria-hidden="true"></i> &nbsp;Browse Brokers'.html_safe, "/employers/employer_profiles/#{@employer_profile.id}/broker_agency", remote: true, class: "btn btn-primary btn-block btn-block btn-lg", id: 'browse_brokers_link',
        onclick: '$("#brokers-empty").hide(); $("#active_broker_tab").hide(); $("#browse_brokers_link").hide()' %>
        <% else %>
          <%= link_to '<i class="fa fa-search" aria-hidden="true"></i> &nbsp;Browse Brokers'.html_safe, ('javascript:;'), class: "btn btn-primary disabled btn-block btn-lg" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row no-buffer">
    <div class="">
      <div id="show_broker_agency"></div>
      <div id="broker_agencies_panel"></div>
    </div>
  </div>

app/views/employers/broker_agency/_fields.html.erb
<div class="table-responsive">
  <table class="table">
    <tr>
      <th>Agency</th>
      <th>Broker</th>
      <th>Broker NPN</th>
      <th>Contact Phone</th>
      <th>Email</th>
    </tr>

    <tr>
      <td><%= broker_agency_profile.legal_name %></td>
      <% if broker_agency_profile.primary_broker_role.present? %>
        <td><%= broker_agency_profile.primary_broker_role.person.full_name %></td>
        <td><%= broker_agency_profile.primary_broker_role.npn %></td>
        <td><%= broker_agency_profile.primary_broker_role.person.phones.map(&:to_s).join('/') %></td>
        <td><a href="mailto:<%= broker_agency_profile.primary_broker_role.person.emails.first.address %>"><%= broker_agency_profile.primary_broker_role.person.emails.first.address %></a></td>
      <% end %>
    </tr>
  </table>
</div>

app/views/employers/broker_agency/_index.html.erb
<h1 class="">Broker Agencies</h1>
<div>
  <div class="row no-buffer">
    <div class="pull-right broker_agencies_search">

      <div class="search-wp">
        <%= render 'shared/search', url: "/employers/employer_profiles/#{@employer_profile.id}/broker_agency", q: @q, remote: true, placeholder: 'Agency/Broker Name, NPN' %>
        <span class="pull-right">
          <a class="broker-advanced-search-options" style="cursor: pointer;">Advanced Options</a>
        </span>
      </div>

      <%= hidden_field_tag "broker_search_url", employers_employer_profile_broker_agency_index_path(@employer_profile) %>

      <div id="advanced_options" style="display: none;">
           <div class="language_multi_select pull-right">
             <%= select_tag(:languages_spoken, options_from_collection_for_select(LanguageList::COMMON_LANGUAGES.sort_by {|lan| lan.common_name}, "iso_639_1", "common_name"), { id: 'broker_agency_language_select', multiple: "multiple" } ) %>
          </div>
          <div>
            <label class="pull-right">
              <%= check_box_tag :working_hours, {id: 'working_hours'} %> Evening/Weekend Availability
            </label>
          </div>
      </div>
    </div>
  </div>

  <h4>Search for a Broker near you. When you find the Broker you want to use, choose 'Select Broker' to hire the Broker.</h4>

  <div class="row no-buffer" id="broker_agencies_listing">
    <%= render "broker_agencies_listing" %>
  </div>
</div>

<script type="text/javascript">
$(function() {

  $(".broker-advanced-search-options").click(function () {
    $("#advanced_options").toggle();
  });

  function searchAgencies(){
    var url = $("#broker_search_url").val();

    var options = {};

    if ($("div.language_multi_select select").val()){
      options['languages'] = $("div.language_multi_select select").val();
    }

    options['q'] = $("div.search-wp input#q").val();

    if ($("#working_hours").is(":checked")){
      options['working_hours'] = 'true';
    }

    $.ajax({
      url: url,
      type: "GET",
      data : options
    });
  }

  $("div.language_multi_select select").change(function(){
    searchAgencies();
  })

  $("#working_hours").change(function(){
    searchAgencies();
  })

  $('#broker_agency_language_select').multiselect({
    nonSelectedText: 'Language(s) spoken',
    maxHeight: 300
  });

  $('#broker_agency_language_select').on('selectric-init', function(event){
    $('.language_multi_select .selectric-wrapper').hide();
  });

});
</script>

app/views/employers/broker_agency/active_broker.js.erb
$("#show_profile").html("<%= escape_javascript render "active_broker" %>");

$('.fade').addClass('in').addClass('active')
$('#inbox').removeClass('active').removeClass('in')
semantic_class();
$('#show_profile').removeClass('hide')