config/routes.rb
  match "hbx_admin/calculate_aptc_csr" => "hbx_admin#calculate_aptc_csr", as: :calculate_aptc_csr, via: :get
  post 'show_hints' => 'welcome#show_hints', :constraints => { :only_ajax => true }

  namespace :users do
    resources :orphans, only: [:index, :show, :destroy]
  end
  
  resources :users do
    member do
      get :reset_password, :lockable, :confirm_lock, :login_history, :change_username_and_email, :edit
      put :confirm_reset_password, :confirm_change_username_and_email, :update
      post :unlock, :change_password
    end
  end

  resources :saml, only: [] do
    collection do
      post :login
      get :logout
      get :navigate_to_assistance
    end
  end

  get 'payment_transactions/generate_saml_response', to: 'payment_transactions#generate_saml_response'

  namespace :exchanges do

    resources :inboxes, only: [:show, :destroy]
    resources :announcements, only: [:index, :create, :destroy] do
      get :dismiss, on: :collection
    end
    resources :agents_inboxes, only: [:show, :destroy]

    resources :residents, only: [:create, :edit, :update] do
      get :search, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :begin_resident_enrollment, on: :collection
      get :resume_resident_enrollment, on: :collection
      get :ridp_bypass, on: :collection
      get :find_sep, on: :collection
    end

    resources :hbx_profiles do
      root 'hbx_profiles#show'

      collection do
        get :family_index
        get :family_index_dt
        get :outstanding_verification_dt
        post :families_index_datatable
        get :employer_index
        get :employer_poc
        post :employer_poc_datatable
        get :employer_invoice
        post :employer_invoice_datatable
        post :generate_invoice
        post :disable_ssn_requirement
        get :broker_agency_index
        get :general_agency_index
        get :issuer_index
        get :product_index
        get :configuration
        post :set_date
        post :update_setting
        get :staff_index
        get :assister_index
        get :request_help
        get :aptc_csr_family_index
        get :binder_index
        get :binder_index_datatable
        post :binder_paid
        get :cancel_enrollment
        post :update_cancel_enrollment
        get :terminate_enrollment
        post :update_terminate_enrollment
        post :add_new_sep
        get :update_effective_date
        get :calculate_sep_dates
        get :add_sep_form
        get :hide_form
        get :show_sep_history
        get :get_user_info
        get :identity_verification
        post :identity_verification_datatable
        get :user_account_index
        get :new_eligibility
      end

      member do
        post :transmit_group_xml
        get :transmit_group_xml
        get :home
        get :inbox
      end

      resources :hbx_staff_roles do
      end
    end

    resources :employer_applications do
      put :terminate
      put :cancel
      put :reinstate
    end

    resources :agents do
      collection do
        get :home
        get :begin_consumer_enrollment
        get :begin_employee_enrollment
        get :resume_enrollment
        get :show
      end
      member do
        get :inbox
      end
    end

    resources :broker_applicants

  end

  namespace :insured do
    get 'verification_documents/upload', to: 'verification_documents#upload'
    post 'verification_documents/upload', to: 'verification_documents#upload'
    get 'verification_documents/download/:key', to: 'verification_documents#download'
    get 'paper_applications/upload', to: 'paper_applications#upload'
    post 'paper_applications/upload', to: 'paper_applications#upload'
    get 'paper_applications/download/:key', to: 'paper_applications#download'
    get 'ridp_documents/upload', to: 'ridp_documents#upload'
    post 'ridp_documents/upload', to: 'ridp_documents#upload'
    get 'ridp_documents/download/:key', to: 'ridp_documents#download'
    resources :ridp_documents, only: [:destroy]

    resources :plan_shoppings, :only => [:show] do
      member do
        get 'plans'
        get 'receipt'
        get 'print_waiver'
        post 'checkout'
        get 'thankyou'
        post 'waive'
        post 'terminate'
        post 'set_elected_aptc'
        get 'plan_selection_callback'
      end
    end

    resources :interactive_identity_verifications, only: [:create, :new, :update] do
      collection do
        get 'failed_validation'
        get 'service_unavailable'
      end
    end

    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :families, only: [:show] do
      get 'new'
      member do
        delete 'delete_consumer_broker'
        get 'generate_out_of_pocket_url'
      end

      collection do
        get 'home'
        get 'manage_family'
        get 'personal'
        get 'inbox'
        get 'brokers'
        get 'verification'
        get 'upload_application'
        get 'document_upload'
        get 'find_sep'
        post 'record_sep'
        get 'check_qle_date'
        get 'check_move_reason'
        get 'check_insurance_reason'
        get 'check_marriage_reason'
        get 'purchase'
        get 'family'
        get 'upload_notice_form'
        post 'upload_notice'
        get 'transition_family_members'
        post 'transition_family_members_update'
      end

      resources :people do
        collection do
          get 'search'
        end
      end
    end

    resources :consumer_role, controller: 'consumer_roles', only: [:create, :edit, :update] do
      get :ssn_taken, on: :collection
      get :search, on: :collection
      get :privacy, on: :collection
      post :match, on: :collection
      post :build, on: :collection
      get :ridp_agreement, on: :collection
      post :update_application_type
      get :upload_ridp_document, on: :collection
      get :immigration_document_options, on: :collection
    end

    resources :employee, :controller=>"employee_roles", only: [:create, :edit, :update, :show] do
      collection do
        get 'new_message_to_broker'
        post 'send_message_to_broker'
        post :match
        get 'search'
        get 'privacy'
        get 'welcome'
      end
    end

    root 'families#home'

    resources :family_members do
      get :resident_index, on: :collection
      get :new_resident_dependent, on: :collection
      get :edit_resident_dependent, on: :member
      get :show_resident_dependent, on: :member
    end

    resources :group_selections, controller: "group_selection", only: [:new, :create] do
      collection do
        post :terminate
        get :terminate_selection
        get :terminate_confirm
      end
    end

  end

  namespace :employers do
    post 'search', to: 'employers#search'
    root 'employer_profiles#new'

    resources :premium_statements, :only => [:show]

    resources :employer_staff_roles, :only => [:create, :destroy] do
      member do
        get :approve
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'match'
      end
    end
    resources :inboxes, only: [:new, :create, :show, :destroy]
    resources :employer_profiles do
      get 'new'
      get 'my_account'
      get 'show_profile'
      get 'link_from_quote'
      get 'consumer_override'
      get 'export_census_employees'
      get 'bulk_employee_upload_form'
      post 'bulk_employee_upload'
      member do
        get "download_invoice"
        post 'generate_checkbook_urls'
      end
      collection do
        get 'welcome'
        get 'search'
        post 'match'
        get 'inbox'
      end
      resources :plan_years do
        get 'reference_plans'
        get 'dental_reference_plans'
        get 'generate_dental_carriers_and_plans'
        get 'plan_details' => 'plan_years#plan_details', on: :collection
        get 'recommend_dates', on: :collection
        get 'reference_plan_options', on: :collection
        post 'revert'
        post 'publish'
        post 'force_publish'
        get 'search_reference_plan', on: :collection
        post 'make_default_benefit_group'
        post 'delete_benefit_group'
        get 'calc_employer_contributions', on: :collection
        get 'calc_offered_plan_contributions', on: :collection
        get 'employee_costs', on: :collection
        get 'reference_plan_summary', on: :collection

      end

      resources :broker_agency, only: [:index, :show, :create] do
        collection do
          get :active_broker
        end
        get :terminate
      end

      resources :census_employees, only: [:new, :create, :edit, :update, :show] do
        get :delink
        get :terminate
        get :rehire
        get :cobra
        get :cobra_reinstate
        get :benefit_group, on: :member
      end
    end
  end

  match 'broker_registration', to: 'broker_agencies/broker_roles#new_broker_agency', via: [:get]

  namespace :carriers do
    resources :carrier_profiles do
    end
  end

  namespace :broker_agencies do
    root 'profiles#new'
    resources :inboxes, only: [:new, :create, :show, :destroy] do
      get :msg_to_portal
    end
    resources :profiles, only: [:new, :create, :show, :index, :edit, :update] do
      get :inbox

      collection do
        get :family_index
        get :employers
        get :messages
        get :staff_index
        get :agency_messages
        get :assign_history
      end
      member do
        get :general_agency_index
        get :manage_employers
        post :clear_assign_for_employer
        get :assign
        post :update_assign
        post :employer_datatable
        post :family_datatable
        post :set_default_ga
      end

      resources :applicants
    end
    resources :broker_roles, only: [:create] do
      root 'broker_roles#new_broker'
      collection do
        get :new_broker
        get :new_staff_member
        get :new_broker_agency
        get :search_broker_agency

app/helpers/consumer_roles_helper.rb
module ConsumerRolesHelper
  def ethnicity_collection
    [
      ["White", "Black or African American", "Asian Indian", "Chinese" ],
      ["Filipino", "Japanese", "Korean", "Vietnamese", "Other Asian"],
      ["Native Hawaiian", "Samoan", "Guamanian or Chamorro", ],
      ["Other Pacific Islander", "American Indian or Alaskan Native", "Other"]

    ].inject([]){ |sets, ethnicities|
      sets << ethnicities.map{|e| OpenStruct.new({name: e, value: e})}
    }
  end

  def latino_collection
    [
      ["Mexican", "Mexican American"],
      ["Chicano/a", "Puerto Rican"],
      ["Cuban", "Other"]
    ].inject([]){ |sets, ethnicities|
      sets << ethnicities.map{|e| OpenStruct.new({name: e, value: e})}
    }
  end

  def find_consumer_role_for_fields(obj)
    if obj.is_a? Person
      obj.consumer_role
    elsif obj.persisted?
      obj.family_member.person.consumer_role
    else
      ConsumerRole.new
    end
  end

  def show_naturalized_citizen_container(obj)
    obj.try(:us_citizen)
  end

  def show_immigration_status_container(obj)
    obj.try(:us_citizen) == false
  end

  def show_tribal_container(obj)
    obj.try(:indian_tribe_member)
  end

  def show_naturalization_doc_type(obj)
    show_naturalized_citizen_container(obj) and obj.try(:naturalized_citizen)
  end

  def show_immigration_doc_type(obj)
    show_immigration_status_container(obj) and obj.try(:eligible_immigration_status)
  end

  def show_vlp_documents_container(obj)
    show_naturalization_doc_type(obj) || show_immigration_doc_type(obj)
  end

  # just work for ivl
  def show_keep_existing_plan(shop_for_plans, hbx_enrollment, new_effective_on)
    return true if hbx_enrollment.is_shop?

    shop_for_plans.blank? && (hbx_enrollment.effective_on.year == (new_effective_on.present? ? new_effective_on.year : nil))
  end

  def is_applying_coverage_value_consumer(use_person, person, consumer_role)
    first_checked = true
    second_checked = false
    if use_person.present?
      first_checked = person.is_applying_coverage == 'true'
      second_checked = person.is_applying_coverage == 'false'
    elsif consumer_role.present?
      first_checked = consumer_role.is_applying_coverage
      second_checked = !consumer_role.is_applying_coverage
    end
    return first_checked, second_checked
  end

  def paper_or_phone_type(id_verified, app_verified, admin_user, consumer )
    if admin_user && (app_verified || id_verified)
      return consumer.admin_bookmark_url
    elsif id_verified
      return consumer.admin_bookmark_url
    end
  end

  def in_person_type(id_verified, admin_user, consumer)
    if admin_user && id_verified
      return consumer.admin_bookmark_url
    elsif id_verified
      return consumer.admin_bookmark_url
    end
  end

  def ridp_redirection_link(person)
    consumer = person.consumer_role
    app_type = person.primary_family.application_type
    admin_user =  current_user.has_hbx_staff_role?
    id_verified = consumer.identity_verified?
    app_verified = consumer.application_verified?
    case app_type
      when 'Paper'
        paper_or_phone_type(id_verified, app_verified, admin_user, consumer )
      when 'In Person'
        in_person_type(id_verified, admin_user, consumer)
      when 'Phone'
        paper_or_phone_type(id_verified, app_verified, admin_user, consumer )
      when 'Curam'
        consumer.admin_bookmark_url
      when 'Mobile'
        return consumer.admin_bookmark_url
      else
        if id_verified
          return consumer.admin_bookmark_url
        end
    end
  end
end

app/helpers/insured/employee_roles_helper.rb
module Insured::EmployeeRolesHelper
  def employee_role_submission_options_for(model)
    if model.persisted?
      { :url => insured_employee_path(model), :method => :put }
    else
      { :url => insured_employee_index_path, :method => :post }
    end
  end

  def coverage_relationship_check(offered_relationship_benefits=[], family_member, new_effective_on )
    return nil if offered_relationship_benefits.blank?
    relationship = PlanCostDecorator.benefit_relationship(family_member.primary_relationship)
    if relationship == "child_under_26" && (calculate_age_by_dob(family_member.dob) > 26 || (new_effective_on.kind_of?(Date) && new_effective_on >= family_member.dob+26.years))
      relationship = "child_over_26"
    end

    offered_relationship_benefits.include? relationship
  end

  def show_market_name_by_enrollment(enrollment)
    return '' if enrollment.blank?

    if enrollment.is_shop?
      enrollment.is_cobra_status? ? 'Employer Sponsored COBRA/Continuation' : 'Employer Sponsored'
    else
      'Individual'
    end
  end
end

app/helpers/insured/family_members_helper.rb
module Insured::FamilyMembersHelper
  def employee_dependent_form_id(model)
    if model.try(:persisted?)
      "add_member_list_#{model.id}"
    else
      "new_employee_dependent_form"
    end
  end

  def employee_dependent_submission_options_for(model)
    if model.try(:persisted?)
      { :remote => true, method: :put, :url => insured_family_member_path(id: model.id), :as => :dependent }
    else
      { :remote => true, method: :post, :url => insured_family_members_path, :as => :dependent }
    end
  end

  def get_address_from_dependent(dependent)
    if dependent.class == FamilyMember
      dependent.person.addresses
    else
      dependent.family_member.person.addresses
    end
  rescue
    []
  end

  def is_applying_coverage_value_dependent(dependent)
    first_checked = true
    second_checked = false
    if dependent.family_member.try(:person).try(:consumer_role).present?
      first_checked = dependent.family_member.person.consumer_role.is_applying_coverage
      second_checked = !dependent.family_member.person.consumer_role.is_applying_coverage
    end
    return first_checked, second_checked
  end
end

app/helpers/insured/plan_filter_helper.rb
module Insured::PlanFilterHelper
  include L10nHelper

  def find_my_doctor
    if @market_kind == "individual" && @coverage_kind == "health"
      link_to('Find Your Doctor','',data: {toggle: "modal", target: "#plan_match_family"})
    elsif @market_kind == "shop" && @coverage_kind == "health"
      link_to('Find Your Doctor', Rails.application.config.checkbook_services_base_url + '/dcshopnationwide/', target: '_blank')
    end
  end

  def estimate_your_costs
    if @market_kind == "shop" && @coverage_kind == "health"
      link_to(l10n("estimate_your_costs"), @dc_checkbook_url , target: '_blank')
    end
  end

end

app/helpers/insured/plan_shopping/receipt_helper.rb
module Insured::PlanShopping::ReceiptHelper
  def show_pay_now?
    return false
    (carrier_with_payment_option? && individual? && (!has_any_previous_kaiser_enrollments? || has_break_in_coverage_enrollments?)) && pay_now_button_timed_out?
  end

  def carrier_with_payment_option?
    @enrollment.plan.carrier_profile.legal_name == 'Kaiser'
  end

  def individual?
    @enrollment.kind.in?(['individual', 'coverall'])
  end

  def pay_now_button_timed_out?
    @enrollment.submitted_at + 15.minutes > TimeKeeper.datetime_of_record
  end

  def has_any_previous_kaiser_enrollments?
    all_kaiser_enrollments = @enrollment.family.enrollments.select { |enr| enr.plan.carrier_profile.legal_name == 'Kaiser' && enr.effective_on.year == @enrollment.effective_on.year }
    enrollments = all_kaiser_enrollments - @enrollment.to_a
    enrollments.present? ? true : false
  end

  def has_break_in_coverage_enrollments?
    @enrollment.family.enrollments.current_year.where(aasm_state: "coverage_terminated").any? { |enr| enr.plan.carrier_profile.legal_name == 'Kaiser' &&  enr.terminated_on.year == @enrollment.effective_on.year && (@enrollment.effective_on - enr.terminated_on) > 1 }
  end
end

app/views/insured/consumer_roles/_consumer_search_form.html.haml
= render 'shared/consumer_search_fields', f: f

%br
#person_search_results

app/views/insured/consumer_roles/_ds_2019_fields.html.erb
<div id="immigration_DS_2019_fields_container">
  <% document = c.object.find_document("DS2019 (Certificate of Eligibility for Exchange Visitor (J-1) Status)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/servis_id", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/i_94_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/passport_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "Passport"} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/country_of_citizenship", locals: {v: v} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_i_20_fields.html.erb
<div id="immigration_temporary_i_20_stamp_fields_container">
  <% document = c.object.find_document("I-20 (Certificate of Eligibility for Nonimmigrant (F-1) Student Status)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/servis_id", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/i_94_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/passport_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "Passport"} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/country_of_citizenship", locals: {v: v} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_i_327_fields.html.erb
<div id="immigration_i_327_fields_container">
  <% document = c.object.find_document("I-327 (Reentry Permit)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/alien_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "I-327"} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_i_551_fields.html.erb
<div id="immigration_i_551_fields_container">
  <% document = c.object.find_document("I-551 (Permanent Resident Card)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/alien_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/card_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "I-551"} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_i_94_fields.html.erb
<div id="immigration_i_94_fields_container">
  <% document = c.object.find_document("I-94 (Arrival/Departure Record)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/i_94_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/servis_id", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "I-94"} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_machine_readable_immigrant_visa_fields.html.erb
<div id="machine_readable_immigrant_visa_fields_container">
  <% document = c.object.find_document("Machine Readable Immigrant Visa (with Temporary I-551 Language)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/alien_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/passport_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/visa_number", locals: {v: v } %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "Temporary I-551"} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/country_of_citizenship", locals: {v: v} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_other_with_i94_fields.html.erb
<div id="immigration_other_with_i94_fields_container">
  <% document = c.object.find_document("Other (With I-94)") %>
  <%= c.fields_for 'vlp_documents', document do |v| %>
    <%= v.hidden_field :subject %>
    <%= v.hidden_field :id %>
    <%= render :partial => "insured/consumer_roles/docs_shared/i_94_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/passport_number", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/servis_id", locals: {v: v} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/expiration_date", locals: {v: v, name: "Passport"} %>
    <%= render :partial => "insured/consumer_roles/docs_shared/country_of_citizenship", locals: {v: v} %>
  <% end %>
</div>

app/views/insured/consumer_roles/_remote_search_form.html.haml
= render 'shared/error_messages', :object => @person
= render "insured/consumer_roles/consumer_search_form", f: f

app/views/insured/consumer_roles/edit.html.erb
<% content_for :horizontal_status do %>
  <%= render :partial => 'insured/families/horizontal_status.html.erb', locals: {step: 1} %>
<% end %>
<%= form_for(@consumer_role.person, url: insured_consumer_role_path(id: @consumer_role.id), :enctype =>"multipart/form-data", html: { multipart: true }, method: :put) do |f| %>
  <%= render partial: "form", locals: {f: f} %>
<% end %>

app/views/insured/consumer_roles/idp_identity_conflict.html.haml
%p
	= l10n(".idp_identity_conflict")

app/views/insured/consumer_roles/new.html.erb
<%= form_for(@person) do |f| %>
  <%= render partial: "form", locals: {f: f} %>
<% end %>

app/views/insured/consumer_roles/privacy.html.erb
<div class="container privacy">
  <h1><%= l10n("your_information") %></h1>  
    <p class="starter">
      We will keep your information private and will not share it with anyone unless you allow it or it is required by law. Your answers will only be used to decide whether you are eligible for health insurance. Information about your health will not be
      used to deny you insurance or determine how much you pay.
      <br/><br/>
      You can complete an application for health insurance for your children or other family members even if you do not qualify yourself. If you are applying for benefits for other members of your family, you will need to give us information about where
      you live, but you are not required to answer any questions about your citizenship or immigration status and you will not have to give us a Social Security Number.
      <br/><br/>
      As part of the application process, we will be checking the information you give us with information from other government agencies like the Social Security Administration, and the Department of Homeland Security. If the information you provide does
      not match the information we get from these agencies, we may ask you to send us proof. Remember, if you are not applying for benefits for yourself, we will not ask you about your citizenship or immigration status and will not check your information
      with the Department of Homeland Security.
      <br/><br/>
      <%= link_to "Learn more about how we will use your information.", "https://www.dchealthlink.com/privacy", target: "_blank" %><br>
      <%= link_to "View Privacy Act Statement", "https://www.dchealthlink.com/privacy-act-statement", target: "_blank" %>

      <br/><br/>
      By clicking Continue, you are saying that you understand that information in this application, and the information we get from data sources will be used to decide the eligibility of the people who are applying for health insurance. You are also
      indicating that you have permission from all of the people listed on the application for their information to be retrieved and used from data sources.
    </p>
  <br>
  <div>
    <%= link_to 'CONTINUE', search_insured_consumer_role_index_path(@search_path), :class => "btn btn-lg btn-primary  interaction-click-control-continue" %>
  </div>
  <br><br>
</div>

app/views/insured/consumer_roles/redirect_to_recover_account.html.haml
%p
	= l10n(".redirect_to_recover_account_msg")